[tool.isort]
line_length = 120
profile = 'black'
py_version=38
skip_glob = [
  ".venv/**",
  "br-*/**",
  "branch-*/**",
  "libs/**",
  "resources/**",
  "stubs/**",
  "typings/**",
  "vendor/**",
  "venv/**",
]

[tool.black]
preview = true
line-length = 120
target-version = ['py38']
exclude = '''
/(
  \.git |
  \.venv |
  language-server |
  plugin/libs |
  resources |
  stubs |
  typings |
  _resources
)/
'''

[tool.pyright]
pythonVersion = '3.11'
